### ISSUE TITLE
Refactor State Store Logic

### ISSUE THREAD

**Issue by DanielMSchmidt** [leehambley/mitre#33]
The target for the refactoring should look like this:

```rust
struct Controller {
  config: Configuration,
  store: StateStore
}

fn from_config(c: Configuration) {
  // init state store and controller
}

impl Controller {
  fn list_all(){} //from state store and fs with state
  fn run(m: Migrations){}
}
```

- `Migration` should be only data
- `Runner` should have state, taking a list of migrations
- `StateStore` should only have functions for getting stored migrations and recording migrations, nothing more

**Comment by leehambley** [comment]
StateStore is removed now https://github.com/leehambley/mitre/pull/39

New model is:

- `trait MigrationList`
- `trait MigrationStorage: MigrationList`
- `struct Migration`
- `trait Runner`
- `struct Engine` (mostly static methods, stateless)
